variable "OD_INSTANCE_COUNT" {}
variable "SPOT_INSTANCE_COUNT" {}
variable "OD_INSTANCE_TYPE" {}
variable "SPOT_INSTANCE_TYPE" {}
variable "COMPONENT" {}
variable "ENV" {}
variable "ALB_ATTACH_TO" {}
variable "PORT" {}
variable "TRIGGER" {}
variable "APP_VERSION" {}
variable "ASG_DESIRED" {}
variable "ASG_MIN" {}
variable "ASG_MAX" {}
